version: '3.8'
services:
  backend:
    build:
      context: '.'
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - my_network
    depends_on:
      - simple_chat_app
  simple_chat_app:
    image: mongo:latest
    container_name: simple_chat_app
    restart: always
    ports:
      - 27017:27017
    volumes:
      - simple_chat_app:/data/db
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
volumes:
  simple_chat_app:
  backend:


